[package]
name = "spotialt-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
tiny_http = { workspace = true }
url = { workspace = true }
open = { workspace = true }
directories = { workspace = true }
parking_lot = { workspace = true }
psst-core = { version = "0.1.0", path = "../../../psst/psst-core", default-features = false, features = ["cpal"] }
